frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

use common\models\Question;
use common\models\QuestionInGame;
use Yii;
use common\models\Game;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * GameController implements the CRUD actions for Game model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    /**
     * Lists all games of authorized user.
     * @return mixed
     */
    public function actionIndex()
    {
        /* @var $user \common\models\User */
        if ($user = Yii::$app->user->getIdentity()) {

            $dataProvider = new ActiveDataProvider([
                'query' => Game::find()->andWhere(['user_id' => $user->id]),
                'sort' => [
                    'defaultOrder' => ['start_game' => SORT_DESC]
                ]
            ]);

            return $this->render('index', [
                'user' => $user,
                'dataProvider' => $dataProvider
            ]);
        }

        return $this->redirect(['site/login']);
    }


    /**
     * @return \yii\web\Response
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */
    public function actionStart()
    {
        Game::startGame();
        return $this->redirect(['next-question']);
    }

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionNextQuestion()
    {
        $question = Game::nextQuestion();
        if ($question) {
            return $this->render('view', [
                'question' => $question,
            ]);
        }
        else throw new NotFoundHttpException('Not found next question');
    }

    /**
     * @param $id
     * @return string
     */
    public function actionSubmitQuestion($id)//id answer from user
    {
        $currentQuestion = Game::submitAnswer($id);

        return $this->render('show-right-answer', [
            'currentQuestion' => $currentQuestion
        ]);
    }

    public function actionGameOver()
    {
        return $this->render('game-over');
    }

    public function actionYouWin()
    {
        return $this->render('you-win');
    }

    public function actionStopGame()
    {
        $game = Game::findCurrentGame();
        $game->stopGame();
        return $this->redirect('index');
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']]
    ];

    if (!Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Games', 'url' => ['game/index']];
    }

    $menuItems[] = ['label' => 'About', 'url' => ['/site/about']];
    $menuItems[] = ['label' => 'Contact', 'url' => ['/site/contact']];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>