common/models/Game.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\NotFoundHttpException;
use yii\web\BadRequestHttpException;



/**
 * This is the model class for table "game".
 *
 * @property integer $id
 * @property integer $start_game
 * @property integer $stop_game
 * @property integer $user_id
 * @property User $user
 * @property integer $current_number_question
 * @property QuestionInGame $currentQuestion
 */
class Game extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'game';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['start_game', 'stop_game', 'user_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'start_game' => 'Start Game',
            'stop_game' => 'Stop Game',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getQuestionsInGame()
    {
        return $this->hasMany(QuestionInGame::className(), ['game_id' => 'id']);
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'start_game',
                'updatedAtAttribute' => false,
            ]
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->user_id = Yii::$app->user->getId();

            return true;
        } else
            return false;
    }

    public function generateQuestions()
    {
        $selectedQuestionIds = [];
        for ($level = 1; $level <= 3; $level++) {
            $allQuestionsIds = Question::find()->andWhere(['level_id' => $level])->column();
            for ($numberOfQuestion = 0; $numberOfQuestion < 5; $numberOfQuestion++) {
                $arrayElement = rand(0, count($allQuestionsIds) - 1);
                $selectedQuestionIds[] = $allQuestionsIds[$arrayElement];
                unset($allQuestionsIds[$arrayElement]);
                sort($allQuestionsIds);
            }

        }
        for ($questionNumber = 0; $questionNumber < count($selectedQuestionIds);
             $questionNumber++
        ) {
            $questionInGame = new QuestionInGame();
            $questionInGame->question_id = $selectedQuestionIds[$questionNumber];
            $questionInGame->question_number = $questionNumber + 1;// numbers of quest must be 1,2,3...
            $questionInGame->save(false);
        }
        $a = 0;
    }

    public function getGeneratedQuestions()
    {
        return $this->hasMany(QuestionInGame::className(), ['game_id' => 'id']);
    }

    /**
     * @return null|QuestionInGame
     */
    public function getCurrentQuestion()
    {
        return QuestionInGame::findOne([
            'game_id' => $this->id,
            'question_number' => $this->current_number_question
        ]);
    }

    /**
     * @param bool $returnFalse
     * @return array|bool|null|\common\models\Game
     * @throws NotFoundHttpException
     */
    public static function findCurrentGame($returnFalse = false)
    {
        if (($model = Game::find(Yii::$app->user->getId())
                ->andWhere([
                    'stop_game' => null,
                    'user_id' => Yii::$app->user->getId()])
                ->one()) !== null
        ) {
            return $model;
        } else {
            if ($returnFalse)
                return false;
            else
                throw new NotFoundHttpException('Such game not found');
        }
    }

    public static function startGame()
    {
        if (!count($allQuestionsIds = Question  ::find()->column())) {
            throw new BadRequestHttpException('Service temporary not contains questions');
        }
        /* @var $game \common\models\Game */
        if ($game = self::findCurrentGame(true)) {
            if (count($game->generatedQuestions) !== 15 ||
                $game->generatedQuestions[0]->game_id != $game->id
            ) {
                QuestionInGame::deleteAll(['game_id' => $game->id]);
                $game->generateQuestions();
            }
        } else {
            $game = new Game();
            $game->save(false);
            $game->generateQuestions();
        }
    }

    /**
     * @return null|\common\models\question
     * @throws NotFoundHttpException
     */
    public static function nextQuestion()
    {
        $game = self::findCurrentGame();

        if ($game->current_number_question){

        }
        else
            $game->current_number_question = 1;
        $game->save(false);

        $question = QuestionInGame::findOne([
            'game_id' => $game->id,
            'question_number' => $game->current_number_question,
        ]);

        return $question;
    }

    public function stopGame()
    {
        $this->stop_game = time();
        $this->save();
    }

    public function gameWin()
    {
        if ($this->currentQuestion->question_number == 15) {
            self::stopGame();
            return true;
        }

        return false;
    }

    /**
     * @param $idUserAnswer
     * @return QuestionInGame
     * @throws NotFoundHttpException
     */
    public static function submitAnswer($idUserAnswer)
    {
        $game = Game::findCurrentGame();

        if ($game->currentQuestion->checkUserAnswer($idUserAnswer)) {
            if ($game->gameWin()) {
                $status = 'win';
                //$game->currentQuestion->gameStatus = 'win';
            }
        } else {
            $game->stopGame();
            //$game->currentQuestion->gameStatus = 'lost';
            $status = 'lost';
        }
        $currentQuestion = $game->currentQuestion;
        $currentQuestion->gameStatus = isset($status) ? $status : null;
        $game->current_number_question++;
        $game->save(false);

        return $currentQuestion;
    }


}

frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

use common\models\Question;
use common\models\QuestionInGame;
use Yii;
use common\models\Game;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * GameController implements the CRUD actions for Game model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    /**
     * Lists all games of authorized user.
     * @return mixed
     */
    public function actionIndex()
    {
        /* @var $user \common\models\User */
        if ($user = Yii::$app->user->getIdentity()) {

            $dataProvider = new ActiveDataProvider([
                'query' => Game::find()->andWhere(['user_id' => $user->id]),
                'sort' => [
                    'defaultOrder' => ['start_game' => SORT_DESC]
                ]
            ]);

            return $this->render('index', [
                'user' => $user,
                'dataProvider' => $dataProvider
            ]);
        }

        return $this->redirect(['site/login']);
    }


    /**
     * @return \yii\web\Response
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */
    public function actionStart()
    {
        Game::startGame();
        return $this->redirect(['next-question']);
    }

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionNextQuestion()
    {
        $question = Game::nextQuestion();
        if ($question) {
            return $this->render('view', [
                'question' => $question,
            ]);
        }
        else throw new NotFoundHttpException('Not found next question');
    }

    /**
     * @param $id
     * @return string
     */
    public function actionSubmitQuestion($id)//id answer from user
    {
        $currentQuestion = Game::submitAnswer($id);

        return $this->render('show-right-answer', [
            'currentQuestion' => $currentQuestion
        ]);
    }

    public function actionGameOver()
    {
        return $this->render('game-over');
    }

    public function actionYouWin()
    {
        return $this->render('you-win');
    }

    public function actionStopGame()
    {
        $game = Game::findCurrentGame();
        $game->stopGame();
        return $this->redirect('index');
    }
}

frontend/views/game/game-over.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Game over.</h1>

        <p class="lead">You did not correctly answer the last question</p>

        <p><?= Html::a('Start new Game', ['game/start'], ['class' => 'btn btn-lg btn-success']) ?></p>
    </div>
</div>

frontend/views/game/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="game-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => \yii\grid\SerialColumn::className()],
            'start_game:dateTime',
            'stop_game:dateTime',
            'current_number_question',

        ]
    ]) ?>

    <p>
        <?= Html::a(\common\models\Game::findCurrentGame(true) ?
            'Continue game' :  'Start new game', ['start'],
            ['class' => 'btn btn-success']) ?>
    </p>


</div>

frontend/views/game/show-right-answer.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 13.02.16
 * Time: 16:15
 */

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $currentQuestion common\models\QuestionInGame */

$this->title = 'Current question: ' . $currentQuestion->question_number;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$question = $currentQuestion->question;
?>
<div class="game-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div>
        <?= $question->text_question ?>
    </div>

    <div>
        <?php foreach ($question->answers as $answer):
                $a = $currentQuestion->user_answer_id;
                $b = $answer->id;
                $c = 0;
            ?>
            <div
            <?= ($answer->id == $currentQuestion->user_answer_id) ? 'style="background:orange"' : '' ?>>
                <?= Html::tag(
                    'p',
                    $answer->text_answer,
                    ['style' => ($question->id_answer_true === $answer->id) ? 'color:green' : 'color:red'])
                ?>
            </div>
        <?php endforeach ?>
    </div>
    <?php
        $options = [];
        switch ($currentQuestion->gameStatus) {
        case 'win':
            $text = 'You win';
            $url = ['you-win'];
            $options = ['class' => 'btn btn-success'];
            break;
        case 'lost':
            $text  = 'Game over';
            $url = ['game-over'];
            $options = ['class' => 'btn btn-danger'];
            break;
        default:
            $text  = 'Next question';
            $url = ['next-question'];
            $options = ['class' => 'btn btn-primary'];
        } ?>

    <p>
        <?= Html::a($text, $url, $options) ?>
    </p>

</div>

frontend/views/game/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $question common\models\QuestionInGame */

$this->title = 'Current question: ' . $question->question_number;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$question = $question->question;
?>
<div class="game-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div>
        <?= $question->text_question ?>
    </div>

    <div>
        <?php foreach ($question->answers as $answer): ?>
        <p>
            <?= Html::a($answer->text_answer, ['submit-question', 'id' => $answer->id]) ?>
        </p>
        <?php endforeach ?>
    </div>

    <div><?= Html::a('Stop game', ['game/stop-game'], ['class' => 'btn btn-danger']) ?></div>

</div>

frontend/views/game/you-win.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have correctly answered all the questions</p>

        <p><?= Html::a('Start new Game', ['game/start'], ['class' => 'btn btn-lg btn-success']) ?></p>
    </div>
</div>